---
config:
  theme: default
  look: neo
  layout: fixed
---
flowchart TD
    A[Início]
    B[1ª Conferência - Elem<br/>• Check de dados, etiquetas, guias<br/>• Carimbo e assinatura]
    C[2ª Conferência - João Victor<br/>• Check duplicado<br/>• Segundo carimbo e assinatura]
    D[Fiscalização - Helen / Ariane<br/>• Verifica carimbos e assinaturas]
    E[Liberar para Dra. Mariana]
    F[Montagem de Lâminas]
    G[Etiquetagem]
    H[Conferência Dupla de Lâminas na Bandeja<br/>• Contagem<br/>• Conferência de coloração<br/>• Correspondência mapa/pedido]
    I[Material pronto para liberação]
    J[Fim]


A --> B --> C --> D --> E --> F --> G --> H --> I --> J

